import StartPage from "@/components/StartPage";
import Header from "@/components/header";
import Projects from "@/components/projects";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Eduardo Fagotti</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Kanit:wght@100;200;300;400&display=swap"
          rel="stylesheet"
        ></link>
      </Head>
      <Header />
      <StartPage />
      <Projects />
    </>
  );
}
